# Generated by Django 2.2.1 on 2019-05-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u1',
            name='dob',
        ),
    ]
